trigger:
- main

variables:
  BUILD_COMMIT: 9e6c6abeba891c37c09a125c4da3b647de14fbed
  ANACONDA_ORG: ofajardo

jobs:
  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-1015
      matrix:
        py_3.7_64:
          MB_PYTHON_VERSION: "3.7"
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
        py_3.9_64:
          MB_PYTHON_VERSION: "3.9"
        py_3.10_64:
          MB_PYTHON_VERSION: "3.10"

  - template: azure/posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-20.04
      matrix:
        py_3.7_64manylinux1:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
        py_3.8_64manylinux1:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
        py_3.9_64manylinux1:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
        py_3.10_64manylinux1:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"

  - template: azure/posix.yml
    parameters:
      name: linuxaarch64
      vmImage: ubuntu-20.04
      matrix:
        py_3.7_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.8_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.9_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.10_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
