trigger:
- main

variables:
  BUILD_COMMIT: ece557b2a583d2083c1739fbf6788738fea02320
  ANACONDA_ORG: ofajardo

jobs:
  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-10.14
      matrix:
        py_3.6_64:
          MB_PYTHON_VERSION: "3.6"
        py_3.7_64:
          MB_PYTHON_VERSION: "3.7"
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
        py_3.9_64:
          MB_PYTHON_VERSION: "3.9"
        py_3.10_64:
          MB_PYTHON_VERSION: "3.10"

  - template: azure/posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-18.04
      matrix:
        py_3.6_32manylinux1:
          MB_PYTHON_VERSION: "3.6"
          PLAT: "i686"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.6_64manylinux1:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "2014"
        py_3.7_32manylinux1:
          MB_PYTHON_VERSION: "3.7"
          PLAT: "i686"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.7_64manylinux1:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
        py_3.8_32manylinux1:
          MB_PYTHON_VERSION: "3.8"
          PLAT: "i686"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.8_64manylinux1:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
        py_3.9_32manylinux1:
          MB_PYTHON_VERSION: "3.9"
          PLAT: "i686"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.9_64manylinux1:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
        py_3.10_32manylinux1:
          MB_PYTHON_VERSION: "3.10"
          PLAT: "i686"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.10_64manylinux1:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"

  - template: azure/posix.yml
    parameters:
      name: linuxaarch64
      vmImage: ubuntu-18.04
      matrix:
        py_3.6_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.7_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.8_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.9_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.10_aarch64manylinux2014:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
          PLAT: "aarch64"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
